Always use route color overrides
opentripplanner/otp-react-redux pull request #1029
Opened 2023-10-11 15:30 UTC by miles-grant-ibigroup

Right now, the color overrides are only used in a few places. This PR examples their use into the route viewer, the itinerary body, and the transitive overlay.

2023-10-18 21:01 UTC, AdrianaCeric approved these changes
Looks good to me

2023-10-20 14:41 UTC, binh-dam-ibigroup approved these changes

2023-10-20 14:42 UTC, binh-dam-ibigroup requested changes
Could you add the updated OTP-UI package that this PR was depending on, please?

2023-10-20 19:00 UTC, binh-dam-ibigroup approved these changes

2023-10-20 19:05 UTC, merged