fix: Filter transit itineraries by including routeModeOverrides
opentripplanner/otp-react-redux pull request #1052
Opened 2023-10-26 18:06 UTC by amy-corson-ibigroup

**Description:**

Includes checking `routeModeOverrides` when sorting transit itineraries. There may be a better/already existing way to do this in which case let me know!

Prevents a live bug where transit trips with override modes are being returned as walk trips.

<img width="175" alt="image" src="https://github.com/opentripplanner/otp-react-redux/assets/115499534/760a3919-bb53-4c59-b31c-4a28483ffece">

**PR Checklist:**
- [n/a] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [n/a] Are all languages supported (Internationalization/Localization)?
- [n/a] Are appropriate Typescript types implemented?

2023-10-27 16:28 UTC, binh-dam-ibigroup commented on lib/components/narrative/narrative-itineraries.js
> +          (leg) => isTransit(leg.mode) | configModeOverrides.includes(leg.mode)
Just curious if there are other places we need to make this change.

2023-10-27 16:40 UTC, binh-dam-ibigroup requested changes

2023-10-27 16:40 UTC, binh-dam-ibigroup commented on lib/components/narrative/narrative-itineraries.js
> +        const configModeOverrides = Object.values(routeModeOverrides)
This line is making Percy tests fail. At least pass `{}` if `routeModeOverrides` is not set.

2023-10-30 18:14 UTC, amy-corson-ibigroup commented
Closed in favor of #1055

2023-10-30 18:14 UTC, closed without merging