Support larger custom route renderers
opentripplanner/otp-react-redux pull request #1079
Opened 2023-11-27 20:34 UTC by miles-grant-ibigroup

**Description:**
Adjusts color handling to be more consistent and allow for more situations

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

2023-11-30 20:50 UTC, daniel-heppner-ibigroup approved these changes
The route colors in transitive are working for me! Looks good

2023-12-04 19:01 UTC, binh-dam-ibigroup requested changes
Should we keep calculating a settings-based route color as fallback?

2023-12-05 15:13 UTC, miles-grant-ibigroup commented on lib/actions/apiV2.js
> -            newRoute.color = getRouteColorBasedOnSettings(
The reason it is removed here is that we instead do the override in every location where the color is used. This gives us more flexibility in how we use the color. Try it! a feed with no color still gets overriden

2023-12-11 22:53 UTC, binh-dam-ibigroup approved these changes
I think my questions have been answered.

2023-12-12 14:41 UTC, merged