Add TOS Link from Config
opentripplanner/otp-react-redux pull request #1080
Opened 2023-11-27 21:05 UTC by amy-corson-ibigroup

**Description:**

Allows a URL override for the Terms of Service that will direct to an external link 

**PR Checklist:**
- [n/a] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [n/a] Are all languages supported (Internationalization/Localization)?
- [x] Are appropriate Typescript types implemented?

2023-12-06 16:38 UTC, binh-dam-ibigroup requested changes
Could you please update the config types? Looks good otherwise.

2023-12-06 16:38 UTC, binh-dam-ibigroup commented on lib/components/user/terms-of-use-pane.tsx
> +  termsOfServiceLink,
Please add `termsOfServiceLink` to the config types. I guess `termsOfStorageSet` needs to be added too.

2023-12-06 16:38 UTC, binh-dam-ibigroup commented on lib/components/user/terms-of-use-pane.tsx
>  const mapStateToProps = (state: any) => {
Use type `AppReduxState`.

2023-12-07 17:23 UTC, AdrianaCeric approved these changes
Great work!

2023-12-07 17:46 UTC, merged