Prevent mobile view change on location clear
opentripplanner/otp-react-redux pull request #1085
Opened 2023-11-30 22:52 UTC by amy-corson-ibigroup

**Description:**
Currently when you clear a location field in mobile view, it resets the view back to the form. This PR changes that so now using the clear location button just clears the location.

Do we need a way to get back to the trip form/map from this view? Should I add a back button that takes you back to the trip form if the location is empty?

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

2023-12-04 23:53 UTC, daniel-heppner-ibigroup requested changes
I think we do need a close or back button here. The browser back button doesn't work to go back to the trip form. :( Sorry

2023-12-11 23:01 UTC, daniel-heppner-ibigroup approved these changes
Ooo yes nicely done! Thanks!

2023-12-12 17:35 UTC, binh-dam-ibigroup commented
@amy-corson-ibigroup Do we need to fix some of the Percy tests?

2023-12-13 23:56 UTC, amy-corson-ibigroup commented
@binh-dam-ibigroup Fixed!

2023-12-15 16:05 UTC, amy-corson-ibigroup commented
As @binh-dam-ibigroup pointed out, the mobile nav bar already has a back arrow, so I've used that instead of creating my own! I've also updated the back arrow to be web accessible but changing it from a `div` to a `button` and adding an `aria-label`

2023-12-15 16:13 UTC, binh-dam-ibigroup approved these changes
> As @binh-dam-ibigroup pointed out, the mobile nav bar already has a back arrow, so I've used that instead of creating my own! I've also updated the back arrow to be web accessible but changing it from a `div` to a `button` and adding an `aria-label`

Nice fix!

2023-12-15 16:13 UTC, binh-dam-ibigroup commented on lib/components/mobile/mobile.css
>    color: white;
Sort CSS

2023-12-15 16:13 UTC, binh-dam-ibigroup commented on lib/components/mobile/navigation-bar.js
> +                <button
Nice

2023-12-15 20:06 UTC, merged