add support for custom settings in calltaker
opentripplanner/otp-react-redux pull request #1094
Opened 2023-12-15 23:34 UTC by daniel-heppner-ibigroup

**Description:**
This PR adds support for custom mode settings in the calltaker advanced options panel. 

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

<img width="572" alt="image" src="https://github.com/opentripplanner/otp-react-redux/assets/92878779/9539fc6d-e014-41b2-84f7-40480bb31092">

2023-12-15 23:34 UTC, daniel-heppner-ibigroup commented
Currently relies on an alpha build

2023-12-15 23:56 UTC, daniel-heppner-ibigroup commented
Actually, I'm going to have @miles-grant-ibigroup review this first because he did some work on these files recently, and I removed some code he wrote.

2023-12-20 16:14 UTC, miles-grant-ibigroup requested changes
Code looks great, nice and clean! Only issue is I don't see how to hide walk reluctance on bike+transit or bikesahre+transit. what do I put in the config? Is this possible?

Also is it possible to go back to the old layout? There's almost no room for results now on high zoom levels/low screen resolutions

2023-12-28 20:15 UTC, daniel-heppner-ibigroup commented
Hm, the layout thing is a problem. I'm not sure how the old layout would work given that there's the ability to have multiple settings. Isn't it fine if the results aren't visible while advanced options are open? 

Otherwise, the reason that walk reluctance is visible is because it's associated with the "transit" mode. We need to add "walk" to the transit only option, then assign walk reluctance mode setting to "walk" instead of "transit". This is the same as the regular mode selector.

2024-01-17 21:32 UTC, daniel-heppner-ibigroup commented
OK, so I made it show the first one in the old position and any extras are displayed below.

2024-01-18 17:17 UTC, miles-grant-ibigroup approved these changes
Great stuff!

2024-01-22 20:33 UTC, daniel-heppner-ibigroup commented
I updated the version of trip-details in this PR to get the new fare changes.

2024-01-23 19:38 UTC, binh-dam-ibigroup approved these changes
LGTM

2024-01-23 19:38 UTC, binh-dam-ibigroup commented on lib/components/form/call-taker/advanced-options.js
> +              key={applicableModeSettings[0].key}
What is the need for the `key` prop here?

2024-01-25 21:01 UTC, merged