Fix colors in route viewer
opentripplanner/otp-react-redux pull request #1109
Opened 2024-01-10 21:00 UTC by amy-corson-ibigroup

**Description:**

Passing origColor through to the Route Viewer! Will also need to be applied to any custom route renderers.

Also took off a couple of pixels that were causing a weird crop on some routes with long names.

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

| Before | After |
|--------|-------|
|![image](https://github.com/opentripplanner/otp-react-redux/assets/115499534/bbb5920a-0ad7-4036-a3bb-3b363a5b6672)|![image](https://github.com/opentripplanner/otp-react-redux/assets/115499534/61b5f017-6d53-448c-bc48-a6df789d2d55)|

2024-01-10 21:03 UTC, miles-grant-ibigroup requested changes
I have a few questions about this PR. Doesn't this defeat the point of route color overrides entirely? Since we're always using `origColor`

2024-01-10 21:03 UTC, miles-grant-ibigroup commented on lib/components/narrative/metro/default-route-renderer.tsx
> +      color={leg.origColor || '333333'}
Woah there! We need to include `routeColor` as a fallback!

2024-01-10 21:03 UTC, miles-grant-ibigroup commented on lib/components/narrative/metro/default-route-renderer.tsx
> +  leg: Leg & { onColoredBackground?: boolean; origColor: string }
```suggestion
  leg: Leg & { onColoredBackground?: boolean; origColor?: string }
```

`origColor` is optional!

2024-01-10 21:15 UTC, amy-corson-ibigroup commented
> I have a few questions about this PR. Doesn't this defeat the point of route color overrides entirely? Since we're always using `origColor`

Definitely open to other suggestions! Using the color variables that are available on `leg` this seemed like the easiest way to make sure the appropriate colors were showing up on each route.

2024-01-10 21:16 UTC, miles-grant-ibigroup commented
> > I have a few questions about this PR. Doesn't this defeat the point of route color overrides entirely? Since we're always using `origColor`
> 
> Definitely open to other suggestions! Using the color variables that are available on `leg` this seemed like the easiest way to make sure the appropriate colors were showing up on each route.

Yes but doesn't this PR disable the route color override functionality? Since we're always using the `origColor`

2024-01-11 18:01 UTC, amy-corson-ibigroup commented
I see what you mean, I think I fixed it!

2024-01-11 18:03 UTC, miles-grant-ibigroup requested changes
This still breaks the functionality! If we set a route color in the config, then don't we want it applied in the route viewer?

2024-01-11 19:03 UTC, amy-corson-ibigroup commented
Okay this should fix the route viewer and allow color overrides by mode

2024-01-11 19:34 UTC, miles-grant-ibigroup approved these changes
Works perfectly in every situation I could throw at it. Well done! Thanks for dealing with all this back and forth. Should be good to go once the snapshots are updated!

2024-01-12 14:51 UTC, binh-dam-ibigroup approved these changes
LGTM

2024-01-12 16:26 UTC, merged