Add Modal + TS to account page
opentripplanner/otp-react-redux pull request #1118
Opened 2024-01-24 23:09 UTC by amy-corson-ibigroup

**Description:**

Adds the `PopupWrapper` to the account settings page so users can submit feedback from account settings. 

Also adds TS to the file.

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

2024-01-25 15:40 UTC, binh-dam-ibigroup requested changes
Use the `subNav` boolean prop and fix the type error on `setPopupContent`, please.

2024-01-25 15:40 UTC, binh-dam-ibigroup commented on lib/components/user/account-page.tsx
> +const mapStateToProps = (state: AppReduxState, ownProps: any) => {
Delete `ownProps`.

2024-01-25 15:40 UTC, binh-dam-ibigroup commented on lib/components/user/account-page.tsx
> +      <AppFrame SubNav={SubNav}>
The `subNav` boolean prop is still needed. It is used to hide the "My account" header and the "Trips/Settings" tabs when saving a trip.

2024-01-25 20:27 UTC, binh-dam-ibigroup approved these changes
Works well, thanks for the changes.

2024-01-26 19:27 UTC, miles-grant-ibigroup approved these changes
Working Great!

2024-01-26 19:40 UTC, merged