Fix TOS link and update Core Utils
opentripplanner/otp-react-redux pull request #1152
Opened 2024-02-26 17:34 UTC by amy-corson-ibigroup

**Description:**
Fixes a broken link in Tagalog translation, and updates core utils package to include monorail.

**PR Checklist:**
- [x] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [x] Are all languages supported (Internationalization/Localization)?
- [x] Are appropriate Typescript types implemented?

2024-02-27 22:07 UTC, binh-dam-ibigroup commented on package.json
> +    "@opentripplanner/core-utils": "11.3.0",
Any reason to pin the core-utils version?
```suggestion
   "@opentripplanner/core-utils": "^11.3.0",
```

2024-02-27 22:08 UTC, binh-dam-ibigroup commented on yarn.lock
> +"@opentripplanner/core-utils@^11.0.2", "@opentripplanner/core-utils@^11.1.3":
Can these core-utils be deduplicated?

2024-02-27 22:08 UTC, binh-dam-ibigroup requested changes
Can you unpin the core-utils version and try deduplicating?

2024-02-29 16:10 UTC, amy-corson-ibigroup commented
Core utils was updated by https://github.com/opentripplanner/otp-react-redux/pull/1148 so this is just correcting the Tagalog link now!

2024-02-29 16:18 UTC, binh-dam-ibigroup approved these changes

2024-02-29 23:01 UTC, daniel-heppner-ibigroup approved these changes
Oops! Good fix

2024-02-29 23:05 UTC, merged