Recenter Nearby View on Map Pan
opentripplanner/otp-react-redux pull request #1170
Opened 2024-03-14 16:03 UTC by miles-grant-ibigroup

**Description:**

Uses the maplibre `moveend` event to load new nearby view data when the map pans. Refactors some things to avoid too many calls

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

2024-03-18 18:54 UTC, binh-dam-ibigroup approved these changes

2024-03-18 18:54 UTC, binh-dam-ibigroup commented on lib/components/viewers/nearby/nearby-view.tsx
> +      // Briefly flash the highlight to alert the user that we've moved
Not the biggest fan of that effect, but that can be improved subsequently.

2024-03-20 17:35 UTC, amy-corson-ibigroup requested changes
I think this is much cleaner if you remove the drag listener entirely and put all of the current drag listener logic under the move listener instead 
1. Often when dragging the map, the map physics can overshoot where the drag stopped. So when the map stops moving, the "map center" we just set is actually nowhere near the center. 
2. Using the `moveend` listener instead means the center is set when the map actually stops moving, and other movements like zoom also affect the map center, which I think is more intuitive.

2024-03-20 18:39 UTC, amy-corson-ibigroup approved these changes
Okay, I see what you mean!! It'd be nice to revisit this in the future, but for now I agree this is the best approach

2024-03-20 18:44 UTC, merged