Nearby View: Add distance to cards
opentripplanner/otp-react-redux pull request #1203
Opened 2024-04-23 15:06 UTC by miles-grant-ibigroup

**Description:**
We get this lovely distance info from OTP but haven't made us of it! Now we show this distance info on the top of all the cards and it helps the user get a picture of where all these things around them actually are.

All types are correctly updated and all colors are a11y checked.

Need a French string/translations.

**PR Checklist:**
- [x] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [x] Are all languages supported (Internationalization/Localization)?
- [x] Are appropriate Typescript types implemented?

2024-04-23 19:06 UTC, binh-dam-ibigroup approved these changes
Looks good with one visual nice-to-have nitpick.

2024-04-24 14:14 UTC, miles-grant-ibigroup commented on lib/components/viewers/nearby/stop-card-header.tsx
> +        <DistanceDisplay distance={stopData.distance} />
Good catch thanks!

2024-04-24 20:48 UTC, daniel-heppner-ibigroup requested changes
This looks very good! I wonder if instead of hiding it for 0 we should say "A few x (feet,steps,meters) away" for things under 5 meters away? 

Sometimes the stop you clicked has a distance >0 (I saw 3 ft), which seems a little awkward.

2024-04-25 17:54 UTC, miles-grant-ibigroup commented
> This looks very good! I wonder if instead of hiding it for 0 we should say "A few x (feet,steps,meters) away" for things under 5 meters away?
> 
> Sometimes the stop you clicked has a distance >0 (I saw 3 ft), which seems a little awkward.

Good call! Fixed

2024-04-30 19:42 UTC, daniel-heppner-ibigroup approved these changes
LGTM! Thanks for the change

2024-05-01 10:49 UTC, merged