Add Class Names
opentripplanner/otp-react-redux pull request #1236
Opened 2024-06-13 15:38 UTC by miles-grant-ibigroup

**Description:**
Adds a bunch of class names all over the place to make post-compile styling easier.

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

2024-08-08 01:00 UTC, daniel-heppner-ibigroup requested changes
This looks pretty good but I have a few thoughts about redundant things. Also I'd like to be able to test it with the new ItinerarySupplement component

2024-08-08 08:33 UTC, miles-grant-ibigroup commented on lib/components/app/app.css
> +  .app-menu .app-menu-nearby-viewer-link,
I think there is a user who wants to style these separately. I also tried to keep changes as minimal as possible

2024-08-08 08:34 UTC, miles-grant-ibigroup commented on lib/components/narrative/metro/attribute-utils.tsx
>  export const getFirstTransitLegStop = (
It's used in the metro itinerary!

2024-08-08 17:04 UTC, daniel-heppner-ibigroup commented on lib/components/narrative/metro/attribute-utils.tsx
>  export const getFirstTransitLegStop = (
If it wasn't clear this comment is about `getFirstTransitLegStop`. Literally all it does is return the stop from an itinerary. I don't know that we really need a whole function to do that. There's no logic there

2024-08-09 10:49 UTC, miles-grant-ibigroup commented on lib/components/narrative/metro/attribute-utils.tsx
>  export const getFirstTransitLegStop = (
It's shorter to write out the method than to copy paste that line everywhere!

2024-08-09 16:52 UTC, daniel-heppner-ibigroup approved these changes

2024-08-14 20:39 UTC, amy-corson-ibigroup approved these changes
I think this makes sense! Beautiful class names

2024-08-15 17:22 UTC, merged