set `viewedRouteStops` when route viewer is active
opentripplanner/otp-react-redux pull request #1270
Opened 2024-09-06 17:12 UTC by miles-grant-ibigroup

**Description:**
Blocked waiting for https://github.com/opentripplanner/otp-ui/pull/772

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

2024-09-17 19:24 UTC, daniel-heppner-ibigroup requested changes
Just clean up the state mapper. I also noticed that sometimes a handful of stops just don't show up. Is that an OTP thing?

2024-09-17 19:24 UTC, daniel-heppner-ibigroup commented on lib/components/map/default-map.tsx
> +            new Set([...cur?.[1]?.stops.map((s) => s.id), ...acc])
I think this can be cleaned up. Remove the Array.from and Set from this and do it outside the reducer so it doesn't have to be repeated on each loop. Also, maybe we can move this to a function above? I found it quite difficult to read what was happening here.

2024-09-17 19:24 UTC, daniel-heppner-ibigroup commented on lib/components/map/default-map.tsx
> +            new Set([...cur?.[1]?.stops.map((s) => s.id), ...acc])
Alternatively just break out more variables. Like put the Object.entries into a variable.

2024-09-19 13:36 UTC, miles-grant-ibigroup commented
Blocked by https://github.com/opentripplanner/otp-react-redux/pull/1270

2024-09-23 15:45 UTC, daniel-heppner-ibigroup approved these changes
Nice thank you!

2024-09-24 18:52 UTC, amy-corson-ibigroup approved these changes
Looks great!!

2024-09-25 15:19 UTC, merged