respect mode text color
opentripplanner/otp-react-redux pull request #1283
Opened 2024-10-09 16:22 UTC by miles-grant-ibigroup

**Description:**
Makes sure mode based text color overrides are used on the map

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

2024-10-26 00:43 UTC, daniel-heppner-ibigroup requested changes

2024-10-26 00:43 UTC, daniel-heppner-ibigroup commented on lib/actions/apiV2.js
> +                          textColor: getRouteTextColorBasedOnSettings(
put this in a const at the top of the map. also refactor `getRouteOperator` into its own variable so it isn't repeated.

2024-10-26 00:43 UTC, daniel-heppner-ibigroup commented on lib/util/viewer.js
> +export function getRouteTextColorBasedOnSettings(operator = {}, route = {}) {
delete this change and revert the file

2024-11-04 23:00 UTC, daniel-heppner-ibigroup approved these changes
alright, this is looking good now. thanks for the fix

2024-11-05 18:37 UTC, amy-corson-ibigroup approved these changes
Beautiful colors!

2024-11-05 20:13 UTC, merged