Overlay Popup Behavior Correction
opentripplanner/otp-react-redux pull request #1288
Opened 2024-10-15 18:31 UTC by miles-grant-ibigroup

**Description:**
The jumping is because of transitive. I couldn't think of a good way to stop transitive from jumping and then thought about what the desired behavior would be without the jumping (just randomly flashing colors) and it also feels really weird so I think the solution is to just disable hover effects altogether. 

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

2024-10-15 21:38 UTC, daniel-heppner-ibigroup requested changes
typescript :(

2024-10-15 21:38 UTC, daniel-heppner-ibigroup commented on lib/components/map/itinerary-summary-overlay.tsx
> +  const midPoints = mergedItins.reduce(
this has an any type. I think `reduce` needs to have a type and `mergedItins` needs to be typed to not get errors.
Either type `narrative-itineraries.js` and `doMergeItineraries()` or assign a type to the variable here.

2024-11-04 21:26 UTC, daniel-heppner-ibigroup approved these changes
fine now because I fixed it

2024-11-04 21:26 UTC, daniel-heppner-ibigroup commented on lib/components/map/itinerary-summary-overlay.tsx
> +  const midPoints = mergedItins.reduce(
it still has an any type
<img width="272" alt="image" src="https://github.com/user-attachments/assets/10a744b5-5371-4b04-99f8-df875e38d1b7">

2024-11-05 18:23 UTC, josh-willis-arcadis approved these changes
Changes look good. Looks like percy tests are failing visual tests? Not sure what is happening there.

2024-11-05 20:13 UTC, miles-grant-ibigroup commented
> Changes look good. Looks like percy tests are failing visual tests? Not sure what is happening there.

Daylight savings!

2024-11-05 20:13 UTC, merged