Consolidate find stop times for stop query
opentripplanner/otp-react-redux pull request #1290
Opened 2024-10-16 15:10 UTC by amy-corson-ibigroup

**Description:**
Removes the shorter query for operators, as it was causing issues with the schedule in the nearby view.

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

2024-10-16 18:25 UTC, josh-willis-arcadis approved these changes
LGTM!

2024-10-16 18:25 UTC, josh-willis-arcadis commented
looks like snapshots need to be cleaned up

2024-10-18 16:52 UTC, miles-grant-ibigroup requested changes
Still seeing a bug. If I go to the schedule view for a stop, then click on a stop popup on the map, I see the weird "Loading Stop...". 

We might need a new approach to getting these icons?

2024-11-14 18:18 UTC, miles-grant-ibigroup approved these changes
I'm so confused how/why this works but it totally does! Yay

2024-11-14 18:18 UTC, miles-grant-ibigroup commented on lib/components/map/default-map.tsx
> +    case 'Stops':
Why is this here?

2024-11-18 14:31 UTC, amy-corson-ibigroup commented on lib/components/map/default-map.tsx
> +    case 'Stops':
Because the otpUi-stopsandstations layer has "Stops" as the name!
<img width="263" alt="image" src="https://github.com/user-attachments/assets/1f83f0d9-cf2e-4781-80d0-1b51df5851cb">

2024-11-18 14:31 UTC, merged