Custom GraphQL and Mobility Profile Routing
opentripplanner/otp-react-redux pull request #1292
Opened 2024-10-17 17:33 UTC by binh-dam-ibigroup

## Description

This PR sets up craco to accept custom plan GraphQL files (or use a default one).
Custom plan query files are passed through the custom `config.js` and placed in the redux state at startup.
For configuration-enabled mobility profiles, that new parameter is added to the variables passed to the GraphQL `plan` query. 

To test, ensure that planning trips with mobility profiles produce different results based on the profiles, and that on configs without mobility profiles, planning trips is not affected.

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

2024-10-18 20:04 UTC, josh-willis-arcadis approved these changes
changes are working with multiple configs with and without mobility profile.

2024-10-30 19:16 UTC, miles-grant-ibigroup requested changes
Overall works, even if it's a bit hacky. Just want to double check a few things!

2024-10-30 19:16 UTC, miles-grant-ibigroup commented on lib/main.js
> +
Do we still need this? Why not just put it in the js config?

2024-10-30 19:16 UTC, miles-grant-ibigroup commented on craco.config.js
> +      // Support YAML
Comment needs updating

2024-10-30 19:16 UTC, miles-grant-ibigroup commented on lib/actions/apiV2.js
> +    }
Do we have a GMAP specific branch for otp-rr? Do we want to bring this into dev?

2024-11-01 12:03 UTC, binh-dam-ibigroup commented on lib/actions/apiV2.js
> +    }
Not yet, although try to move specific stuff to config would be best.

2024-11-01 12:04 UTC, binh-dam-ibigroup commented on lib/main.js
> +
This puts the custom query into the redux state, so it can be retrieved from actions.

2024-11-01 12:14 UTC, binh-dam-ibigroup commented on craco.config.js
> +      // Support YAML
Thanks, updated in https://github.com/opentripplanner/otp-react-redux/pull/1292/commits/37260077aab004d45b0ced9dbef13c10226dbb8c

2024-11-01 12:14 UTC, binh-dam-ibigroup commented on lib/main.js
> +
I updated the comment in https://github.com/opentripplanner/otp-react-redux/pull/1292/commits/e60f6942111a56e4be995cdb0349a5522f30d94a.

2024-11-04 16:07 UTC, miles-grant-ibigroup approved these changes
A bit nervous about this but it seems to work alright...

2024-11-06 15:23 UTC, merged