feat(trusted-companions): Plan trip with mobility profile for self or on behalf of trusted companion
opentripplanner/otp-react-redux pull request #1302
Opened 2024-11-08 17:28 UTC by josh-willis-arcadis

**Description:**
Allows a user to plan a trip according to a mobility profile for their self or on behalf of a trusted companion. 

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

2024-11-18 20:42 UTC, binh-dam-ibigroup requested changes
A few things to clean up at first sight, knowing that changes from #1289 need to be merged first.

2024-11-18 20:42 UTC, binh-dam-ibigroup commented on lib/actions/user.js
> +    console.log('data::::::', data)
Remove console statement.

2024-11-18 20:42 UTC, binh-dam-ibigroup commented on lib/components/form/advanced-settings-panel.tsx
> +  loggedInUser: User | null
Use the `?:` syntax for optional attributes.

2024-11-18 20:42 UTC, binh-dam-ibigroup commented on lib/components/form/advanced-settings-panel.tsx
> +  console.log('state:::', state)
Remove console log

2024-11-18 20:42 UTC, binh-dam-ibigroup commented on lib/components/form/advanced-settings-panel.tsx
> +              onChange={(e) => {
Use `useCallback` for this handler.

2024-11-18 20:42 UTC, binh-dam-ibigroup commented on lib/components/form/advanced-settings-panel.tsx
> +                  text: 'Myself',
Add i18n entry.

2024-11-18 20:42 UTC, binh-dam-ibigroup commented on lib/components/user/monitored-trip/saved-trip-screen.js
> +                  hasMobilityProfile={Boolean(loggedInUser.mobilityProfile)}
This needs to come from config (it might not be initially populated if users skip steps in the account setup).

2024-11-21 14:54 UTC, binh-dam-ibigroup approved these changes
Few nitpicks but it seems to work!

2024-11-21 14:54 UTC, binh-dam-ibigroup commented on lib/components/form/advanced-settings-panel.tsx
> +const Subheader = styled.h2<{ invisible?: boolean }>`
Can we have a separate `styled.h2` for visible subheaders?

2024-11-21 14:54 UTC, binh-dam-ibigroup commented on lib/components/form/advanced-settings-panel.tsx
> +  loggedInUser?: User | null
I think you can remove `null`.

2024-11-21 14:54 UTC, binh-dam-ibigroup commented on lib/components/form/advanced-settings-panel.tsx
> +        loggedInUser.dependentsInfo.length > 0 && (
I think you can write the whole thing as `loggedInUser?.dependentsInfo?.length`

2024-11-21 14:54 UTC, binh-dam-ibigroup commented on lib/components/form/advanced-settings-panel.tsx
> +    loggedInUser: state.user.loggedInUser || null,
You can remove `null` here too.

2024-11-21 15:20 UTC, binh-dam-ibigroup commented on i18n/en-US.yml
> +        according  to their mobility profile. To add travel companions, visit
At this time, there is no mechanism to add a "dependent" person to an account as this text might suggest (the "dependent" person, for which we are planning trips for, has to add the companion first), so the second part of the label could be removed for now.

2024-11-22 15:49 UTC, binh-dam-ibigroup commented on i18n/en-US.yml
> +        according  to their mobility profile.
Remove extra space.

2024-12-03 18:15 UTC, amy-corson-ibigroup requested changes
SO sorry for how long it took me to review this! Just a few cleanup things, but the bones look good!

2024-12-03 18:15 UTC, amy-corson-ibigroup commented on lib/components/form/advanced-settings-panel.tsx
> +const MobilityProfileContainer = styled.div`
The spacing and indenting here is looking really random. Can we 
1. Make the spacing even between d/t selector above and mode selector below (I think you can make this much higher, there's a lot of vertical space here you can use!)
2. Make all the left-hand padding uniform and in line with the other elements around it 
<img width="477" alt="image" src="https://github.com/user-attachments/assets/139a1903-4435-4548-b504-beac23c27639">

2024-12-03 18:15 UTC, amy-corson-ibigroup commented on lib/components/form/advanced-settings-panel.tsx
> +`
This doesn't seem to be used anywhere

2024-12-03 18:15 UTC, amy-corson-ibigroup commented on lib/components/form/advanced-settings-panel.tsx
> +  margin-bottom: 12px;
I actually don't think this `12px` is doing anything, but regardless I think this spacing between this and the mode selector could be much higher!

2024-12-03 21:27 UTC, josh-willis-arcadis commented on lib/components/form/advanced-settings-panel.tsx
> +`
good catch!

2024-12-05 21:53 UTC, josh-willis-arcadis commented on lib/components/form/advanced-settings-panel.tsx
> +const MobilityProfileContainer = styled.div`
addressed in [fe2c134](https://github.com/opentripplanner/otp-react-redux/pull/1302/commits/fe2c1340f5c6a92ff572c53ec51cd4d0bf170a1c)

2024-12-10 18:15 UTC, amy-corson-ibigroup approved these changes
Looks really good! Thank you for the changes

2024-12-10 20:06 UTC, merged