auto-set sort direction on sort type change
opentripplanner/otp-react-redux pull request #1315
Opened 2024-12-03 19:28 UTC by miles-grant-ibigroup

Sets ASC/DESC automatically on changing the sort type. 

Do we want this behavior like this by default? Curious for opinions

2024-12-10 19:07 UTC, amy-corson-ibigroup requested changes
On a new search, when I set d/t to "depart" I'm consistently getting this blank dropdown 
![image](https://github.com/user-attachments/assets/b7e02b8c-f11f-472f-bed1-6957e234d928)

2024-12-13 19:21 UTC, miles-grant-ibigroup commented
Blocked by https://github.com/opentripplanner/otp-react-redux/pull/1316

2024-12-19 17:49 UTC, miles-grant-ibigroup commented
All is fixed after latest merge!

2024-12-19 22:37 UTC, amy-corson-ibigroup approved these changes
Looks good!

2024-12-20 18:16 UTC, binh-dam-ibigroup approved these changes

2024-12-20 18:16 UTC, binh-dam-ibigroup commented on lib/components/form/date-time-modal.tsx
> +export const DepartArriveDirectionMap: Record<
Maybe rename to `DepartArriveDefaultSortMap` or something like this, to clarify it is a default setting?

2024-12-26 12:49 UTC, merged