Prevent constant updating in nearby view
opentripplanner/otp-react-redux pull request #1324
Opened 2024-12-13 20:21 UTC by amy-corson-ibigroup

**Description:**

Fixes constant rerendering of the nearby view by only updating `currentPosition` if the user moves .0001 lat/long away from their initial position. 

Is this the most efficient way to do this? Should this instead be set in the nearby view? Should we potentially calc the km distance between the two points instead, to make it more geographically consistent? Open to a lot of feedback on this 

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

2024-12-16 21:42 UTC, daniel-heppner-ibigroup requested changes
- Update snapshots
- Fix percy tests
- Maybe add a comment that talks about approximately what the distance of .001 lat/lon is. I think it depends on location

Maybe we should just not update the position based on currentPosition changes?

2024-12-16 21:42 UTC, daniel-heppner-ibigroup commented on lib/components/viewers/nearby/nearby-view.tsx
> +  console.log(nearbyItemList)
remove this!

2024-12-16 23:44 UTC, amy-corson-ibigroup commented on lib/components/viewers/nearby/nearby-view.tsx
> +  console.log(nearbyItemList)
Oops!

2024-12-16 23:45 UTC, amy-corson-ibigroup commented
Changes to the percy snapshots are being caused by changes to the `h3`! Before the invisible header was taking up space, now it's not

2024-12-17 00:37 UTC, daniel-heppner-ibigroup approved these changes
Thanks for the fixes!

2024-12-17 19:51 UTC, miles-grant-ibigroup approved these changes
Looks and works great! Wonderful work. Just one minor nitpick

2024-12-17 19:51 UTC, miles-grant-ibigroup commented on lib/components/app/responsive-webapp.js
> +          if (shouldUpdate) {
You can inline this. It's only used once

2024-12-18 16:46 UTC, merged