Fix toast for companion updates
opentripplanner/otp-react-redux pull request #1331
Opened 2024-12-20 18:56 UTC by binh-dam-ibigroup

## Description

Fix #1330

## PR Checklist
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

| Before | After |
    |--------|-------|
    | ![before screenshot](https://github.com/user-attachments/assets/3c9dc159-319d-49cb-a83b-9f80e8569704) |  ![image](https://github.com/user-attachments/assets/09a7b7fa-1cab-49e4-8b66-5972362fc1cc) |

2024-12-26 18:54 UTC, amy-corson-ibigroup approved these changes
Thanks for the changes!

2024-12-26 20:31 UTC, josh-willis-arcadis requested changes
Toast is working. I think the text should be changed to match the section header. Also I noticed when updating a users mobility profile the toast does not include a header. 
<img width="731" alt="image" src="https://github.com/user-attachments/assets/edb6262a-4e65-41f9-821f-f04fc6eeb48a" />

2024-12-26 20:31 UTC, josh-willis-arcadis commented on i18n/en-US.yml
> +      add-companion-form: Companions
I think this should say 'Travel Companions' to match the header of that section.

2025-01-06 18:52 UTC, binh-dam-ibigroup commented on i18n/en-US.yml
> +      add-companion-form: Companions
Updated in https://github.com/opentripplanner/otp-react-redux/pull/1331/commits/bca731f1d67ebbc9620cdd89593c7a4eb1eee327.

2025-01-06 19:00 UTC, binh-dam-ibigroup commented
> Also I noticed when updating a users mobility profile the toast does not include a header

Do you think there should be a header there too? "Settings" and "Mobility Profile" for their respective sections?

2025-01-09 16:36 UTC, josh-willis-arcadis commented
> > Also I noticed when updating a users mobility profile the toast does not include a header
> 
> Do you think there should be a header there too? "Settings" and "Mobility Profile" for their respective sections?

I think so. Every other section has a header in the toast except for this section.

2025-01-09 21:23 UTC, binh-dam-ibigroup commented
> > > Also I noticed when updating a users mobility profile the toast does not include a header
> > 
> > 
> > Do you think there should be a header there too? "Settings" and "Mobility Profile" for their respective sections?
> 
> I think so. Every other section has a header in the toast except for this section.

Updated in https://github.com/opentripplanner/otp-react-redux/pull/1331/commits/d9a00f41109b478db00fb58df676fd4625754824.

2025-01-09 21:56 UTC, josh-willis-arcadis approved these changes
TY for the changes. Looks great!

2025-01-09 21:57 UTC, merged