Refactor user actions
opentripplanner/otp-react-redux pull request #246
Opened 2020-10-02 22:11 UTC by binh-dam-ibigroup

This PR extracts the code to parse middleware configuration vars,
and inlines methods previously in `utils/middleware`.

2020-10-05 06:11 UTC, evansiroky commented on lib/actions/user.js
> + * @param functionToExecute the code to execute, with parameters (dispatch, arguments)
Please note that `functionToExecute` can be a function that can be awaited upon.

2020-10-05 06:14 UTC, evansiroky approved these changes
Just one comment about a comment

2020-10-05 14:24 UTC, landonreed requested changes
This approach is far too clever. I really disagree with how the `executeWithMiddleware` method body is structured and how it is invoked throughout `user.js`.

2020-10-06 13:53 UTC, binh-dam-ibigroup commented
> This approach is far too clever. I really disagree with how the `executeWithMiddleware` method body is structured and how it is invoked throughout `user.js`.

It highlights the core logic for these actions and hides repeat code to extract and check common variables.

2020-10-09 17:41 UTC, evansiroky requested changes
I'm going to have to change my review to request changes. I kind of agree with Landon in that this introduces a bit too much abstraction/overhead. I think the `executeWithMiddleware` shouldn't exist and instead it should simply be a util function that makes sure the middleware config exists and if so returns the desired middleware data given the getState method.

2020-10-15 15:28 UTC, merged

2020-10-30 18:13 UTC, landonreed commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/otp-react-redux)
- [GitHub release](https://github.com/opentripplanner/otp-react-redux/releases/tag/v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: