Fix scrolling and overflow in route viewer.
opentripplanner/otp-react-redux pull request #321
Opened 2021-01-28 22:25 UTC by binh-dam-ibigroup

This PR fixes #320.

2021-02-02 19:39 UTC, evansiroky approved these changes

2021-02-04 21:22 UTC, landonreed requested changes
This is on the right track, but we need to add css to some inner div (not sure which) to get an ellipsis on overflow. Also, the title prop should be populated with the route name value.

2021-02-12 16:24 UTC, landonreed approved these changes

2021-02-12 16:25 UTC, landonreed commented
@binh-dam-ibigroup, I'm going to go ahead and merge. I don't think the changes since @evansiroky's review really warrant another look from him.

2021-02-12 16:25 UTC, merged