fix(deps): update otp-ui location field to 1.8.0
opentripplanner/otp-react-redux pull request #491
Opened 2021-11-08 02:44 UTC by daniel-heppner-ibigroup

The 1.7.0 location field update introduced street names to business/place search results, however the street names didn't show up in other locations, like the itinerary or saved trips. This update fixes that, so those results will propagate everywhere. For old saved trips, or for URLs (with query params) saved before this update, users will still see the old names.

2021-11-08 03:01 UTC, daniel-heppner-ibigroup commented
Can someone take a look at the yarn.lock? Not sure about the geocoder- looks like one version got removed in the git merge.

2021-11-08 11:13 UTC, miles-grant-ibigroup requested changes
Looks good, thanks for updating this! The yarn.lock issues might come down to one of the otp-ui dependencies having an older version of geocoder as a dependency. I ran `yarn install` locally and it made some changes to the lock file that looked productive. That might resolve the issue? Otherwise we can try to run [yarn-deduplicate](https://github.com/atlassian/yarn-deduplicate)

2021-11-10 19:14 UTC, daniel-heppner-ibigroup commented
yarn.lock looking correct now?

2021-11-11 11:53 UTC, miles-grant-ibigroup commented
Lockfile is definitely looking better, but I think now is probably a good a time as any to run `yarn-deduplicate -s fewer` which should clean things up a bit, since I've been having similar lockfile issues elsewhere.

2021-11-12 09:25 UTC, miles-grant-ibigroup approved these changes
Looks wonderful now, thanks for all these adjustments!

2021-11-17 17:01 UTC, merged