Update localisation of config error message overrides
opentripplanner/otp-react-redux pull request #495
Opened 2021-11-08 20:47 UTC by philip-cline

This PR brings error message handling in line w/ the localization updates in #480, moving the custom error messages under the `language` config heading so that they are imported with other overrides. It was separated into its own PR based on conversation in #480 [here](https://github.com/opentripplanner/otp-react-redux/pull/480#discussion_r743515715):

2021-11-09 14:04 UTC, miles-grant-ibigroup approved these changes
Looks amazing thank you! Some of these diffs are so satisfying

2021-11-09 20:03 UTC, binh-dam-ibigroup requested changes
See suggestion to use `injectIntl` once.

2021-11-09 20:26 UTC, philip-cline commented on lib/components/narrative/narrative-itineraries-errors.js
> +  const intl = useIntl()
Here, don't we need the hook in order to pass the intl object to `getErrorMessage`

2021-11-09 20:28 UTC, philip-cline commented on lib/components/narrative/narrative-itineraries-errors.js
> +  const intl = useIntl()
Or are you suggesting using the `<ErrorMessage />` component rather than getErrorMessage here

2021-11-09 20:59 UTC, binh-dam-ibigroup commented on lib/components/narrative/narrative-itineraries-errors.js
> +  const intl = useIntl()
Yes, have only the `ErrorMessage` component use `injectIntl`. The call to `getErrorMessage` can probably remain where it is.

2021-11-09 23:06 UTC, binh-dam-ibigroup approved these changes
One small change and it should be good to go.

2021-11-09 23:06 UTC, binh-dam-ibigroup commented on lib/components/mobile/results-error.js
> +      </div>
Please revert this change.

2021-11-11 21:50 UTC, philip-cline commented on lib/components/form/error-message.js
> +const ErrorMessage = ({ error, message }) => {
@binh-dam-ibigroup I noticed mapping the error message in mapState with injectIntl wouldn't work bc the ownProps.intl was not defined yet. Moved injectIntl to a useIntl hook and refactored.

2021-11-11 21:51 UTC, philip-cline commented on lib/components/form/error-message.js
> +const ErrorMessage = ({ error, message }) => {
Tests will continue to fail pending some FormattedTime fixes I have to make in the main branch so if this change is ok, I'll merge this and keep working on the `react-intl-ramp-up-pr3` branch

2021-11-16 15:08 UTC, merged