Upgrade @opentripplanner/trip-details to 2.0.0
opentripplanner/otp-react-redux pull request #508
Opened 2021-11-30 15:45 UTC by binh-dam-ibigroup

This PR adds support i18n in the `TripDetails` component.

2021-12-01 15:39 UTC, philip-cline requested changes
Few small comments on formatting, and I think @miles-grant-ibigroup figured out what to do to get the tests passing. 

Use of the number skeletons and special tokens in plurals looks great. I'll update the i18n clean-up PR to use these as well so things are standardized.

2021-12-01 19:29 UTC, binh-dam-ibigroup commented
The a11y build should be fixed now thanks to @miles-grant-ibigroup's finding, but awaiting #509 to remove the failing lint-docs step.

2021-12-03 14:13 UTC, binh-dam-ibigroup commented on i18n/en-US.yml
> +    caloriesDescription: "Calories burned is based on
Sure. Updated in https://github.com/opentripplanner/otp-react-redux/pull/508/commits/4343bafdece1097102b632748352a11fdcaeaedf.

2021-12-03 14:13 UTC, binh-dam-ibigroup commented on i18n/fr-FR.yml
> +    caloriesDescription: "La dépense calorique est calculée sur la base de
Sure. Updated in https://github.com/opentripplanner/otp-react-redux/pull/508/commits/4343bafdece1097102b632748352a11fdcaeaedf.

2021-12-03 16:37 UTC, philip-cline approved these changes

2021-12-03 21:42 UTC, daniel-heppner-ibigroup approved these changes

2021-12-06 13:31 UTC, merged