feat(Flex Itineraries, Config): Add config param to disable flex arc …
opentripplanner/otp-react-redux pull request #549
Opened 2022-02-18 22:07 UTC by philip-cline

…display

This PR makes use of a configuration parameter (which would be put under the transitive section) to disable displaying a flex route arc (as requested by NYSDOT). 

Relies on OPT-UI PR: https://github.com/opentripplanner/otp-ui/pull/352
and makes use of the following configuration PR: https://github.com/ibi-group/configurations/pull/209/files

2022-02-22 22:10 UTC, miles-grant-ibigroup requested changes
Looks good, nice and clean!

Just one quick question about a possible error in the example config

2022-02-22 22:10 UTC, miles-grant-ibigroup commented on example-config.yml
> +  ### - disableFlexArc: optional parameter to disable rendering flex itinerary legs as an arc.
wait are there 2 ways to enable this?

2022-02-28 18:05 UTC, miles-grant-ibigroup approved these changes
Looking great! Sorry for the delay on this

2022-03-02 17:56 UTC, daniel-heppner-ibigroup approved these changes

2022-03-02 19:01 UTC, merged