Remove flags from LocaleSelector
opentripplanner/otp-react-redux pull request #567
Opened 2022-03-10 16:40 UTC by philip-cline

This PR removes flags from the `LocaleSelector` component. Flags are replaced by the language name, which is bolded if selected (checkbox removed). 

A small improvement to the locale state update is made as well, which only updates the state with a matched (supported) locale. This allows bolding of the used language on initialization, as well as preventing a bug where custom messages are not imported before language selection. 

A related PR (https://github.com/ibi-group/configurations/pull/234) removes the flags from the ATL-RIDES QA config

2022-03-11 15:01 UTC, binh-dam-ibigroup commented on lib/actions/ui.js
> +    const matchedLocale = getMatchingLocaleString(effectiveLocale, 'en-US')
Not sure what happened here, the locale/language switching does not seem to work.
Also, using the URL to switch the locale (e.g. by appending `?locale=fr`) no longer works.

2022-03-11 15:02 UTC, binh-dam-ibigroup requested changes
Something broke along the way. Please advise regarding https://github.com/opentripplanner/otp-react-redux/pull/567/files#r824797351.

2022-03-11 17:24 UTC, philip-cline commented
Thanks, didn't push the change with passing configLocales to getMatchingLocaleString. This should be working now

2022-03-11 19:34 UTC, binh-dam-ibigroup approved these changes
Nice!

2022-03-14 14:27 UTC, miles-grant-ibigroup approved these changes
Looks good and works for me! Just one small nit about the color. I have feelings about the bold as well but I think that's more productive as part of an upcoming redesign

2022-03-14 14:27 UTC, miles-grant-ibigroup commented on lib/components/app/locale-selector.tsx
> +      title={<Icon style={{ color: '#fff' }} type="globe" />}
Super nit, but could we make the color `color: rgba(255, 255, 255, 0.85);`? This lets some of the bg bleed through (while still being accessible!) and matches the view switcher

2022-03-14 15:41 UTC, merged