Fix stop marker
opentripplanner/otp-react-redux pull request #746
Opened 2023-01-05 22:12 UTC by binh-dam-ibigroup

This PR fixes rendering of the stop markers shown on the map when the stop viewer is active:
- Caret position is fixed
- Active stop is shown on top
- When switching stops using nearby stops, the new active stop is shown in black and not gray.

2023-01-06 16:23 UTC, miles-grant-ibigroup requested changes
Corrected borders look great! I'm a huge fan.

Just have some small regressions and other potential fixes we might want to address while we're here

2023-01-06 16:25 UTC, binh-dam-ibigroup commented on lib/components/map/enhanced-stop-marker.js
> +    modeColors
That got lost in some prior change (the ATL QA deployment does not seem to use mode colors).

2023-01-06 16:26 UTC, binh-dam-ibigroup commented on lib/components/map/map.css
> +  z-index: 100;
Oops

2023-01-06 16:41 UTC, binh-dam-ibigroup commented on lib/components/map/map.css
> +  z-index: 100;
Fixed in https://github.com/opentripplanner/otp-react-redux/pull/746/commits/969836e9e57c4091b8709a810b2a4e2ca2846102, thanks for catching that.

2023-01-09 12:40 UTC, miles-grant-ibigroup commented on lib/components/map/enhanced-stop-marker.js
> +    modeColors
Sounds good we can bring this back in the future.

2023-01-09 12:41 UTC, miles-grant-ibigroup approved these changes
Works great! Thanks for the cleanup

2023-01-11 14:42 UTC, amy-corson-ibigroup approved these changes
Looks really nice!

2023-01-11 15:17 UTC, merged