Accomodate for Different Headsign Naming
opentripplanner/otp-react-redux pull request #794
Opened 2023-02-15 19:17 UTC by AdrianaCeric

Not all route pattern names follow the `'49 to <Destination> (<destid>)[ from <Origin> (<originid)]'` format. This PR adds an additional conditional that checks if the route name doesn't have an open bracket and uses the route's `shortName` to generate the correct headsign name.

Co-authored by: Miles G.

2023-02-15 19:19 UTC, miles-grant-ibigroup commented on lib/util/viewer.js
> +    console.log(routeShortName)
Whoops I think this slipped in!

2023-02-15 19:22 UTC, AdrianaCeric commented on lib/util/viewer.js
> +    console.log(routeShortName)
Lol. good catch

2023-02-16 13:37 UTC, binh-dam-ibigroup requested changes
Could you add a unit test for this change? (so we can see relevant examples in the code).

2023-02-17 14:54 UTC, AdrianaCeric commented
@binh-dam-ibigroup I wrote unit tests, where should I put them?

2023-02-17 15:21 UTC, binh-dam-ibigroup commented
> @binh-dam-ibigroup I wrote unit tests, where should I put them?

@AdrianaCeric Put them in new file `__tests__/util/viewer.js`. (See other js files in `__tests__` for how unit tests are written.)

2023-02-17 18:31 UTC, binh-dam-ibigroup approved these changes
Nice, thanks for the changes!

2023-02-17 20:55 UTC, philip-cline approved these changes
LGTM. Unit tests were helpful and well written. Happy to see sesame street get some rapid transit.

2023-02-17 21:24 UTC, merged