Basic a11y Support for Trip Settings
opentripplanner/otp-react-redux pull request #816
Opened 2023-03-07 04:14 UTC by demory

Basic a11y support for trip settings form including current mode selector plus "gear" and date/time dropdown containers (actual dropdown content will be in otp-ui)

**PR Checklist:**
- [ ] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [ ] Are all languages supported (Internationalization/Localization)?
- [ ] Are appropriate Typescript types implemented?

2023-03-07 12:48 UTC, miles-grant-ibigroup requested changes
Have repaired the Percy tests. Still want to block this because of some issues I'm seeing when there are fewer mode buttons. <img width="254" alt="Screenshot 2023-03-07 at 7 47 50 AM" src="https://user-images.githubusercontent.com/86619099/223426434-f39b7b9e-9a33-4597-a236-e03300028e31.png">

2023-03-09 22:26 UTC, demory commented
@miles-grant-ibigroup I fixed the date/time selector preview button clipping issue (which I could only reproduce on Safari) and made the styling consistent with the mode and gear buttons.

But I cannot reproduce the clipped mode button, even with fewer (2) modes enabled. Can you share what config changes are causing that for you?

2023-03-10 16:04 UTC, miles-grant-ibigroup approved these changes
All bugs are fixed and things work well! Thanks for this cleanup. Tests will pass once https://github.com/opentripplanner/otp-react-redux/pull/818 is merged

2023-03-14 16:43 UTC, amy-corson-ibigroup approved these changes

2023-03-14 16:55 UTC, merged