Feat: Clickable Navbar Agency Logo
opentripplanner/otp-react-redux pull request #855
Opened 2023-04-12 14:24 UTC by AdrianaCeric

**Description:**
Navbar agency logo can now be configured to either redirect to a specified link or refresh the page

**Testing:**
Add The following to a configuration to test for refresh:

```
navBar:
  doesLogoRefresh: true
  doesLogoRedirectToUrl: false
  urlThatLogoRedirectsTo: https://example.com/
```
and the following to test for a url redirect:
```
navBar:
  doesLogoRefresh: false
  doesLogoRedirectToUrl: true
  urlThatLogoRedirectsTo: https://example.com/
```
⚠️ The button role doesn't work for screen readers and I'm not sure why??

**PR Checklist:**
- [x] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [x] Are all languages supported (Internationalization/Localization)?
- [x] Are appropriate Typescript types implemented?

2023-04-12 14:25 UTC, AdrianaCeric commented on i18n/en-US.yml
> +      {co2} {isMore, select, true {more} other {less} } CO₂ than driving alone
I don't remember making this change, I think it's ESLint?

2023-04-13 16:24 UTC, binh-dam-ibigroup requested changes
I think the code can be simplified a good bit.

2023-04-13 16:24 UTC, binh-dam-ibigroup commented on lib/components/app/desktop-nav.tsx
> +              style={{
This prop should not be necessary.

2023-04-13 16:24 UTC, binh-dam-ibigroup commented on lib/components/app/desktop-nav.tsx
> +  const _resetAndShowTripPlanner = () => {
Can this be combined with the other "Start Over" code?

2023-04-17 14:05 UTC, AdrianaCeric commented on lib/components/app/desktop-nav.tsx
> -              {/* A title is always rendered (e.g.for screen readers)
I removed this since it was a repeat of a comment starting at line 33

2023-04-19 14:01 UTC, AdrianaCeric commented on lib/components/app/desktop-nav.tsx
> +              onClick={handleClick}
will be hard to do that without causing the logo to refresh onClick and redirect to link at same time

2023-04-19 14:15 UTC, AdrianaCeric commented on lib/components/app/desktop-nav.tsx
> +    doesLogoRedirectToUrl: state.otp.config?.navBar?.doesLogoRedirectToUrl,
That makes sense, I'll try to do that

2023-04-26 18:41 UTC, AdrianaCeric commented
Closed in favour of https://github.com/opentripplanner/otp-react-redux/pull/868

2023-04-26 18:41 UTC, closed without merging