Survey Modal A11y
opentripplanner/otp-react-redux pull request #896
Opened 2023-05-11 19:50 UTC by amy-corson-ibigroup

**Description:**
- Adds a close button to survey modal
- Modal is now dismissed on esc
- Duplicate `role="dialog"` removed

**PR Checklist:**
- [x] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [x] Are all languages supported (Internationalization/Localization)?
- [x] Are appropriate Typescript types implemented?

2023-05-12 13:10 UTC, binh-dam-ibigroup approved these changes
LGTM!

2023-05-12 13:11 UTC, binh-dam-ibigroup commented on lib/components/app/popup.tsx
> +import { X } from '@styled-icons/bootstrap/X'
Just a side comment that the "Close" icon in the app menu is just CSS.

2023-05-12 15:04 UTC, amy-corson-ibigroup commented
Just an update, I added an `aria-label` to the `role="dialog"` container per some client feedback

2023-05-15 14:12 UTC, miles-grant-ibigroup requested changes
Looks and works great thanks for the changes! Just one opportunity to avoid re-adding the same feature twice

2023-05-15 14:12 UTC, miles-grant-ibigroup commented on lib/components/app/popup.tsx
> +      onEscapeKeyDown={hideModal}
Well done finding this!

2023-05-16 15:29 UTC, amy-corson-ibigroup commented on lib/components/app/popup.tsx
> +const CloseModalButton = styled.button`
Good idea! Added in [8f0078f](https://github.com/opentripplanner/otp-react-redux/pull/896/commits/8f0078fb1583ef560ff2796f9644ecbcdf9d7342)

2023-05-16 18:35 UTC, miles-grant-ibigroup commented on lib/components/app/popup.tsx
> +const CloseModalButton = styled.button`
As discussed offline, we should re-do all of the x buttons at some point in the future. Glad they share some code now!

2023-05-16 18:36 UTC, miles-grant-ibigroup approved these changes
Looking grand

2023-05-16 18:50 UTC, merged