Update dependencies
opentripplanner/otp-react-redux pull request #980
Opened 2023-08-22 18:27 UTC by amy-corson-ibigroup

**Description:**
- Updates OTP-UI dependencies
- Updates `create-OTP-reducer` to avoid crash

**PR Checklist:**
- [n/a] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [n/a] Are all languages supported (Internationalization/Localization)?
- [n/a] Are appropriate Typescript types implemented?

2023-08-22 20:17 UTC, daniel-heppner-ibigroup approved these changes
LGTM, thanks for the updates!

2023-08-23 16:41 UTC, miles-grant-ibigroup requested changes
Just a few comments!

2023-08-23 16:41 UTC, miles-grant-ibigroup commented on lib/components/narrative/metro/default-route-renderer.tsx
> +  const routeTitle = leg.routeShortName || leg.routeLongName
I think `leg.route` is sometimes a value. Can we do `leg?.route` instead?

2023-08-23 16:41 UTC, miles-grant-ibigroup commented on lib/components/narrative/metro/default-route-renderer.tsx
> +  const routeTitle = leg.routeShortName || leg.routeLongName
and while we're at it `leg?.routeShortName` and `leg?.routeShortName`

2023-08-23 16:41 UTC, miles-grant-ibigroup commented on package.json
> +    "@opentripplanner/core-utils": "^11.0.0",
Once we're upgrading can we please also update `itinerary-body`? `yarn upgrade -S @opentripplanner --latest` should give us all we need

2023-08-23 16:42 UTC, miles-grant-ibigroup commented
Also snapshots need to be updated!

2023-08-28 18:28 UTC, merged