Un-de-duplicate headsigns in pattern viewer
opentripplanner/otp-react-redux pull request #997
Opened 2023-09-13 19:13 UTC by miles-grant-ibigroup

**Description:**

Headsign de-duplication previously removed headsigns from the pattern viewer dropdown that were duplicated. However, this caused deviations or short runs to sometimes not be selectable. The long term solution should obviously be to show all patterns, grouped by direction. For now, we append the last stop of the pattern so that they are differentiable. 

**PR Checklist:**
- [x] Does the code follow accessibility standards (WCAG 2.1 AA Compliant)?
- [x] Are all languages supported (Internationalization/Localization)?
- [x] Are appropriate Typescript types implemented?

2023-09-15 16:54 UTC, amy-corson-ibigroup approved these changes
Looks nice!

2023-09-15 16:54 UTC, amy-corson-ibigroup commented on lib/components/viewers/styled.ts
> -      max-width: 300px;
Good catch this was making things weird!

2023-09-15 16:54 UTC, amy-corson-ibigroup commented on lib/components/viewers/route-details.tsx
> +      // Remove duplicate headsigns. Replaces duplicate headsigns with the last stop name
Nitpicky but we're not technically removing anything anymore right, just appending the last stop

2023-09-19 17:34 UTC, AdrianaCeric requested changes
Ok so I am sort of understanding what's going on here, but how does appending the last stop help in the case that two patterns start at different stops and end at the same stop (e.g. South Lake Union Streetcar)?
![image](https://github.com/opentripplanner/otp-react-redux/assets/62163307/f860598c-9497-4abe-9b48-5a09151ab160)
![image](https://github.com/opentripplanner/otp-react-redux/assets/62163307/997cb5b3-9a53-42e2-a051-a9e4f6d7bec4)

2023-09-21 11:10 UTC, miles-grant-ibigroup commented
Yes @AdrianaCeric it doesn't cover this use case but it does cover other cases

2023-09-21 13:11 UTC, AdrianaCeric approved these changes
👍

2023-09-25 19:54 UTC, merged